export const EVENT_DEPENDENCIES_CHECKED = "event.dependencies_checked"
export const EVENT_SYNC_SNIPPETS = "event.sync_snippets"
export const EVENT_SNIPPETS_LOADED = "event.snippets_loaded"
export const EVENT_RUN_SNIPPET = "event.run_snippet"
export const EVENT_SNIPPET_RUN = "event.snippet_run"