export const SETTINGS_SECTION = 'settings'
export const SETTINGS_SHOW_DIFFS = 'show_diffs'
export const SHOW_DIFFS_ALWAYS_SHOW = 'always_show'
export const SHOW_DIFFS_NEVER_SHOW = 'never_show'
export const SHOW_DIFFS_ASK_ME = 'ask_me'
