export const EVENT_RUN_SNIPPET = "event.run_snippet"
export const EVENT_SNIPPET_RUN = "event.snippet_run"
export const EVENT_SHOW_SNIPPET_DIFF = "event.show_snippet_diff"
export const EVENT_SNIPPET_DIFF_SHOWN = "event.snippet_diff_shown"
export const EVENT_COMMIT_DIFF = "event.commit_diff"
export const EVENT_DIFF_COMMITTED = "event.diff_committed"
export const EVENT_SYNC_SNIPPETS = "event.sync_snippets"

export const SET_PATH = "SET_PATH"
export const SET_SNIPPETS_STORE = "SET_SNIPPETS_STORE"
export const SET_CURRENT_SNIPPET_ID = "SET_CURRENT_SNIPPET_ID"
export const SET_LOADING = "SET_LOADING"
export const SET_GENERATED_SNIPPET = "SET_GENERATED_SNIPPET"
export const SET_SHOW_FORM = "SET_SHOW_FORM"